/*-
 * #%L
 * EMnify Java SDK
 * %%
 * Copyright (C) 2021 EMnify
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


/*
 * {{site.brand.api_name}}
 * Rest API resources of the {{site.brand.system_name}}.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.emnify.sdk.model;

import com.emnify.sdk.model.EndpointStatus;
import com.emnify.sdk.model.IpAddressSpace;
import com.emnify.sdk.model.ServiceProfile;
import com.emnify.sdk.model.Sim;
import com.emnify.sdk.model.TariffProfile;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Endpoint
 */
public class EndpointTest {
    private final Endpoint model = new Endpoint();

    /**
     * Model tests for Endpoint
     */
    @Test
    public void testEndpoint() {
        // TODO: test Endpoint
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'serviceProfile'
     */
    @Test
    public void serviceProfileTest() {
        // TODO: test serviceProfile
    }

    /**
     * Test the property 'tariffProfile'
     */
    @Test
    public void tariffProfileTest() {
        // TODO: test tariffProfile
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'ipAddressSpace'
     */
    @Test
    public void ipAddressSpaceTest() {
        // TODO: test ipAddressSpace
    }

    /**
     * Test the property 'sim'
     */
    @Test
    public void simTest() {
        // TODO: test sim
    }

    /**
     * Test the property 'imei'
     */
    @Test
    public void imeiTest() {
        // TODO: test imei
    }

    /**
     * Test the property 'imeiLock'
     */
    @Test
    public void imeiLockTest() {
        // TODO: test imeiLock
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
