name: Documentation generation CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'EMnify SDK  version'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Javadoc Action
        run: mvn javadoc:aggregate -Ppublic-javadoc "-Demnifyjavasdk.version=${{ github.event.inputs.version }}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apidocs
