name: Java CI
on:
  pull_request:
    branches: '**'
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run the Maven install phase
        run: mvn --batch-mode install
      - name: Run the Maven verify phase for the examples
        run: mvn -f examples/quota-management --batch-mode --update-snapshots verify
